### ISSUE TITLE
RobotComponents

### ISSUE THREAD

**Issue by arjendeetman** [robin-gdwl/Robots-in-Grasshopper#3]
The information for RobotComponents is incorrect. RobotComponents has support for external axes...

**Comment by robin-gdwl** [comment]
Better late than never: I added this information. There will be a restructuring of the information in the coming weeks. A lot of information is still missing at the moment.
You can also create a pull-request if you want to update the information yourself.
Check back in a few weeks and everything should be much more detailed and up to date.
